### ISSUE TITLE
Potentially unnecessary babel plugin

### ISSUE THREAD

**Issue by michaelKurowski** [Lukasz-Semik/cash-organizer#2]
https://github.com/Lukasz-Semik/cash-organizer/blob/80172dbca7300976928c065acc55a32c57a762f0/.babelrc#L4
Where do you use it?

**Comment by Lukasz-Semik** [comment]
for example in reducer. 
 return {
        ...state,
        oneShots
      }

**Comment by michaelKurowski** [comment]
ok
